server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: GeoLocateAPI

  main:
    banner-mode: "off"

  output:
    ansi:
      enabled: always

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.synchlabs.GeoLocateAPI: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%thread]){magenta} %clr(%-5level){%highlight} %clr(%logger{36}){cyan} - %clr(%msg){faint}%n"

external:
  providers:
    ip-api:
      url: http://ip-api.com/json

    nominatim:
      reverse-url: https://nominatim.openstreetmap.org/reverse

    open-meteo:
      search-url: https://geocoding-api.open-meteo.com/v1/search

  timeout-ms: 3000

